using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace ai_scheduler.src
{
    public enum Operation
    {
        TRANSFORM,
        TRANSFER
    }

    public enum ResourceKind
    {
        Raw,
        Created,
        Waste
    }

    public class Utils
    {
        private static double _GAMMA_VALUE = .9;
        private static double _C_VAL_FAILURE_COST = .8;       
        private static double _K_VAL_LOGISTICS_FN = 1;
        public const double X_0_LOGISTICS_FN = 0;

        // The state quality reduction factor for the waste generated by a country
        // If there are more electronic waste created by a country, it'll reduce the overall state quality more
        public const double ELECTRONICS_WASTE_WEIGHT_REDUCTIONFACTOR = .1;
        public const double WASTE_MATERIAL_WEIGHT_REDUCTIONFACTOR = .05;
       
        public static double GAMMA_VALUE
        {
            get { return _GAMMA_VALUE; }
            set { _GAMMA_VALUE = value; }
        }

        public static double C_VAL_FAILURE_COST
        {
            get { return _C_VAL_FAILURE_COST; }
            set { _C_VAL_FAILURE_COST = value; }
        }

        public static double K_VAL_LOGISTICS_FN
        {
            get { return _K_VAL_LOGISTICS_FN; }
            set { _K_VAL_LOGISTICS_FN = value; }
        }

        public static int GenerateRandomInt(int min, int max)
        {
            Random rand = new Random();
            int randInt = rand.Next(min, max);
            return randInt;
        }
    }
}
